"""
ProblemProgram: The genotype of our evolutionary framework.

Each program is a Python function that takes a seed and returns (problem_text, answer).
Programs use inverse construction: answer is chosen first, then the problem is built from it.
"""

import hashlib
import json
import os
import importlib.util
import tempfile
import traceback
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class ProblemInstance:
    """A single (problem, answer) pair generated by a program."""
    problem: str
    answer: str
    program_id: str
    seed: int
    verified: bool = False


@dataclass
class ProblemProgram:
    """
    A problem generation program — the unit of evolution.
    
    Contains Python source code that defines a `generate(seed: int) -> (str, str)` function.
    The function uses inverse construction to produce (problem_text, answer_text) pairs.
    """
    source_code: str
    program_id: str = ""
    parent_id: str = ""
    generation: int = 0
    fitness: float = 0.0
    h_score: float = 0.0
    p_hat: float = 0.0
    rq_score: float = 0.0
    niche_h: int = -1       # MAP-Elites H-axis index
    niche_div: int = -1     # MAP-Elites diversity-axis index
    metadata: dict = field(default_factory=dict)

    def __post_init__(self):
        if not self.program_id:
            self.program_id = self._compute_id()

    def _compute_id(self) -> str:
        return hashlib.md5(self.source_code.encode()).hexdigest()[:12]

    def execute(self, seed: int, timeout: float = 10.0) -> Optional[ProblemInstance]:
        """
        Execute the program with the given seed to produce a (problem, answer) pair.
        Returns None if execution fails.
        """
        import signal

        def _timeout_handler(signum, frame):
            raise TimeoutError("Program execution timed out")

        # Write source to temp file and execute
        try:
            # Create a module from source code
            spec = importlib.util.spec_from_loader("gen_module", loader=None)
            module = importlib.util.module_from_spec(spec)

            # Add safe imports to the module namespace
            safe_globals = {
                "__builtins__": __builtins__,
                "math": __import__("math"),
                "random": __import__("random"),
                "fractions": __import__("fractions"),
                "itertools": __import__("itertools"),
                "functools": __import__("functools"),
            }
            # Try to add sympy if available
            try:
                safe_globals["sympy"] = __import__("sympy")
            except ImportError:
                pass

            module.__dict__.update(safe_globals)

            # Set timeout
            old_handler = signal.signal(signal.SIGALRM, _timeout_handler)
            signal.alarm(int(timeout))

            try:
                exec(self.source_code, module.__dict__)

                if not hasattr(module, "generate"):
                    return None

                result = module.generate(seed)

                if not isinstance(result, (tuple, list)) or len(result) != 2:
                    return None

                problem_text, answer_text = str(result[0]), str(result[1])

                if not problem_text.strip() or not answer_text.strip():
                    return None

                return ProblemInstance(
                    problem=problem_text,
                    answer=answer_text,
                    program_id=self.program_id,
                    seed=seed,
                )
            finally:
                signal.alarm(0)
                signal.signal(signal.SIGALRM, old_handler)

        except Exception as e:
            return None

    def generate_batch(self, seeds: list[int]) -> list[ProblemInstance]:
        """Generate multiple problem instances from different seeds."""
        instances = []
        for seed in seeds:
            inst = self.execute(seed)
            if inst is not None:
                instances.append(inst)
        return instances

    def to_dict(self) -> dict:
        return {
            "source_code": self.source_code,
            "program_id": self.program_id,
            "parent_id": self.parent_id,
            "generation": self.generation,
            "fitness": self.fitness,
            "h_score": self.h_score,
            "p_hat": self.p_hat,
            "rq_score": self.rq_score,
            "niche_h": self.niche_h,
            "niche_div": self.niche_div,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "ProblemProgram":
        return cls(**d)

    def save(self, path: str):
        with open(path, "w") as f:
            json.dump(self.to_dict(), f, indent=2, ensure_ascii=False)

    @classmethod
    def load(cls, path: str) -> "ProblemProgram":
        with open(path) as f:
            return cls.from_dict(json.load(f))
