_wandb:
    value:
        cli_version: 0.23.1
        e:
            xiflp6py0swkvdhdt55c7dnb9lpxaa64:
                args:
                    - --node-ip-address=175.115.52.15
                    - --node-manager-port=37681
                    - --object-store-name=/tmp/ray/session_2026-04-08_14-56-23_557675_1051995/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2026-04-08_14-56-23_557675_1051995/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=58594
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=54072
                    - --gcs-address=175.115.52.15:62354
                    - --session-name=session_2026-04-08_14-56-23_557675_1051995
                    - --temp-dir=/tmp/ray
                    - --webui=127.0.0.1:8265
                    - --cluster-id=187c537718a872193727e368b452b7e8f769fd259e9c0425154de287
                    - --startup-token=32
                    - --worker-launch-time-ms=1775627789756
                    - --node-id=8f3c2a4e8c179a05d95c1e00d612cd69a66279d8809932594e54699a
                    - --runtime-env-hash=-364307942
                    - --enable-resource-isolation=false
                cpu_count: 112
                cpu_count_logical: 224
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1851906863104"
                        used: "1404913758208"
                email: yhoon113@gmail.com
                executable: /data/kwon113/envs/venv/bin/python
                git:
                    commit: 150ba234a2514a6f9392f3924a85f0dbf7629564
                    remote: https://github.com/kwon13/evo-sample.git
                gpu: NVIDIA H200
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-4cd41448-88c2-b10c-555b-f72a5a53d783
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-9e485cc7-9ca1-be29-5896-58cba74648c6
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-53727612-c083-dc06-4a07-8baf51480ad0
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-cb9462ca-c7ba-e7dd-5ce6-0be2e5c835ec
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-cd9c39bf-9007-e01e-d728-1fae92131e72
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-d8efdc6d-57b9-9019-2ac0-dd888f37a829
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-3b73a8c9-0e83-9c82-646d-b7a9258a95d8
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-4790301a-e7ac-ac50-6c6b-15d8f8ddc50c
                host: super
                memory:
                    total: "2164108419072"
                os: Linux-5.15.0-119-generic-x86_64-with-glibc2.35
                program: /data/kwon113/envs/venv/lib/python3.11/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.11.13
                root: /data/kwon113/evo-sample
                startedAt: "2026-04-08T05:58:41.236276Z"
                writerId: xiflp6py0swkvdhdt55c7dnb9lpxaa64
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 30
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 30
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.13
            "5": 0.23.1
            "6": 5.4.0
            "12": 0.23.1
            "13": linux-x86_64
ablation:
    value:
        enable_questioner: true
        enable_solver: true
        enable_validation: true
algorithm:
    value:
        adv_estimator: reinforce_plus_plus
        disable_kl: false
        dist_lambda: 1
        frontier_L: 0.3
        frontier_U: 0.7
        gamma: 1
        kl_coef: 0.01
        kl_horizon: 0
        kl_penalty: low_var_kl
        kl_target: 0
        kl_type: fixed
        lam: 1
        mock_data: ""
        use_kl_loss: false
data:
    value:
        answer_key: answer
        execution_timeout_sec: 5
        filter_overlong_prompts: true
        format_prompt: null
        image_key: images
        max_pixels: 4194304
        max_prompt_length: 1024
        max_response_length: 2048
        min_pixels: 262144
        override_chat_template: null
        prompt_key: prompt
        rollout_batch_size: 32
        seed: 1
        shuffle: true
        train_files: ""
        val_batch_size: 500
        val_files: ./data/math500_val.parquet
rq:
    value:
        candidates_per_evo: 8
        crossover_ratio: 0.2
        evolution_freq: 50
        evolution_pct: 0.1
        h_range:
            - 0
            - 5
        h_threshold: 0.1
        in_depth_ratio: 0.5
        instances_per_program: 16
        max_evo_attempts: 64
        n_h_bins: 6
        num_rollouts: 10
        seed_programs_dir: ./seed_programs
        target_hard_champions: 6
        ucb_c: 1
trainer:
    value:
        code_validation_batch_size: 8
        code_validation_dataset_path: null
        code_validation_timeout_sec: 2
        code_validation_workers: 8
        critic_warmup: 0
        default_local_dir: /data/kwon113/evo-sample/rq_output/verl_ckpt
        experiment_name: qwen3_4b_base_rpp
        load_checkpoint_path: null
        logger:
            - console
            - wandb
        max_steps: 2
        n_gpus_per_node: 4
        nnodes: 1
        project_name: rq_evolve
        save_checkpoint_path: /data/kwon113/evo-sample/rq_output/verl_ckpt
        save_every_epoch: true
        save_freq: -1
        save_limit: -1
        total_epochs: 1
        val_before_train: true
        val_every_epoch: false
        val_freq: -1
        val_generations_to_log: 0
        val_mode: reward
        val_only: false
worker:
    value:
        actor:
            clip_ratio_dual: 3
            clip_ratio_high: 0.3
            clip_ratio_low: 0.2
            disable_kl: false
            fsdp:
                enable_cpu_offload: false
                enable_full_shard: true
                enable_rank0_init: false
                fsdp_size: -1
                mp_buffer_dtype: fp32
                mp_param_dtype: bf16
                mp_reduce_dtype: fp32
                torch_dtype: bfloat16
                use_orig_params: false
            global_batch_size: 32
            global_batch_size_per_device: -1
            kl_coef: 0.01
            kl_penalty: low_var_kl
            max_grad_norm: 1
            micro_batch_size_per_device_for_experience: 2
            micro_batch_size_per_device_for_update: 2
            model:
                enable_gradient_checkpointing: true
                freeze_vision_tower: false
                model_path: Qwen/Qwen3-4B-Base
                tokenizer_path: Qwen/Qwen3-4B-Base
                trust_remote_code: true
            offload:
                offload_optimizer: false
                offload_params: false
            optim:
                betas:
                    - 0.9
                    - 0.999
                lr: 1e-06
                lr_warmup_ratio: 0
                min_lr_ratio: null
                strategy: adamw
                training_steps: 2
                warmup_style: constant
                weight_decay: 0.01
            padding_free: false
            ppo_epochs: 1
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_kl_loss: false
            use_torch_compile: false
        critic:
            cliprange_value: 0.5
            fsdp:
                enable_cpu_offload: false
                enable_full_shard: true
                enable_rank0_init: false
                fsdp_size: -1
                mp_buffer_dtype: fp32
                mp_param_dtype: bf16
                mp_reduce_dtype: fp32
                torch_dtype: null
                use_orig_params: false
            global_batch_size: 256
            global_batch_size_per_device: -1
            max_grad_norm: 1
            micro_batch_size_per_device_for_experience: 16
            micro_batch_size_per_device_for_update: 4
            model:
                enable_gradient_checkpointing: true
                freeze_vision_tower: false
                model_path: null
                tokenizer_path: null
                trust_remote_code: true
            offload:
                offload_optimizer: false
                offload_params: false
            optim:
                betas:
                    - 0.9
                    - 0.999
                lr: 1e-06
                lr_warmup_ratio: 0
                min_lr_ratio: null
                strategy: adamw
                training_steps: 2
                warmup_style: constant
                weight_decay: 0.01
            padding_free: false
            ppo_epochs: 1
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
        hybrid_engine: true
        ref:
            fsdp:
                enable_cpu_offload: false
                enable_full_shard: true
                enable_rank0_init: false
                fsdp_size: -1
                mp_buffer_dtype: fp32
                mp_param_dtype: bf16
                mp_reduce_dtype: fp32
                torch_dtype: bfloat16
                use_orig_params: false
            micro_batch_size_per_device_for_experience: 2
            offload:
                offload_optimizer: false
                offload_params: false
            padding_free: false
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_torch_compile: false
        reward:
            num_cpus: 1
            reward_function: /data/kwon113/evo-sample/reward_fn.py
            reward_function_name: compute_score
            reward_type: batch
            skip_special_tokens: true
        rollout:
            disable_log_stats: true
            dtype: bfloat16
            enable_chunked_prefill: false
            enforce_eager: false
            gpu_memory_utilization: 0.5
            ignore_eos: false
            limit_images: 0
            max_model_len: 4096
            max_num_batched_tokens: 8192
            multi_turn_questioner: false
            multi_turn_turn2_system: null
            multi_turn_turn2_user: null
            "n": 1
            name: vllm
            prompt_length: 1024
            response_length: 2048
            seed: 1
            solver_sampling_n: 1
            solver_temperature: 0.8
            temperature: 0.7
            tensor_parallel_size: 1
            top_k: -1
            top_p: 1
            trust_remote_code: true
            verifier_temperature: 0
        solver_reward:
            num_cpus: 1
            reward_function: null
            reward_function_name: null
            reward_type: batch
            skip_special_tokens: true
